###GET tasks
GET http://localhost:3001

###Add new task
POST http://localhost:3001/new HTTP/1.1
Content-Type: application/json

###Delete task
DELETE http://localhost:3001/delete/1 HTTP/1.1

{
    "description": "TEST from REST client"
}